apiVersion: apps/v1
kind: Deployment
metadata:
  name: greetvandewynckele-deployment
  namespace: greetvandewynckele
spec:
  replicas: 3
  selector:
    matchLabels:
      app: greetvandewynckele
  template:
    metadata:
      labels:
        app: greetvandewynckele
    spec:
      containers:
        - name: greetvandewynckele
          image: your-registry/react-static-app:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: greetvandewynckele-svc
  namespace: greetvandewynckele
spec:
  selector:
    app: greetvandewynckele
  ports:
    - protocol: TCP
      port: 443
      targetPort: 80
  type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: greetvdw-httproute
  namespace: greetvandewynckele
spec:
  parentRefs:
    - name: greetvdw-gw
      namespace: istio-ingress
  hostnames:
    - "greetvandewynckele.com"
    - "*.greetvandewynckele.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: greetvandewynckele-svc
          port: 443
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: greetvdw-gw
  namespace: istio-ingress
spec:
  gatewayClassName: istio
  listeners:
    - name: https-greetvdw
      hostname: "greetvandewynckele.com"
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - name: greetvdw-cert
            namespace: istio-ingress
            group: ""
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: greetvandewynckele
    - name: https-greetvdw-wc
      hostname: "*.greetvandewynckele.com"
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - name: greetvdw-cert
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: greetvandewynckele
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci-sa
  namespace: greetvandewynckele
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: greetvandewynckele
  name: ci
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: greetvdw-ci-sa-binding
  namespace: greetvandewynckele
subjects:
  - kind: ServiceAccount
    name: ci-sa
    namespace: greetvandewynckele
roleRef:
  kind: Role
  name: ci
  apiGroup: rbac.authorization.k8s.io
