name: Docker Image CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
      with:
        registry: ghcr.io
        username: arnoldvann
        password: ${{ secrets.GHCR_PAT_GVDW }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/arnoldvann/greetvandewynckele

    - name: Build and push the Docker image
      uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          ${{ steps.meta.outputs.tags }}
          ghcr.io/arnoldvann/greetvandewynckele:${{ github.sha }}
        labels: ${{ steps.meta.outputs.labels }}

  deploy:

    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Setup Kubeconfig
      run: |
        mkdir $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
        chmod 600 $HOME/.kube/config
        
    - name: Update deployment image and rollout
      run: |
        kubectl set image deployment/greetvandewynckele-deployment greetvandewynckele=ghcr.io/arnoldvann/greetvandewynckele:${{ github.sha }} -n greetvandewynckele
        kubectl rollout status deployment/greetvandewynckele -n greetvandewynckele
